version: 2

orbs:
  heroku: circleci/heroku@1.0.1

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test:
        requires:
          - build
    - start_deploy:
          type: approval
          requires:
            - test
    - heroku_deploy:
          requires:
            - start_deploy
          jobs:
            - heroku/deploy-via-git
            
jobs:
  build:
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: chmod permissions
          command: sudo chmod +x ./gradlew

      - run: ./gradlew build

      - persist_to_workspace:
          root: .
          paths:
            - build
  test:
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: chmod permissions
          command: sudo chmod +x ./gradlew
          
      - run: ./gradlew test