version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

workflows:
  java-ci-cd:
    jobs:
      - build
      - test:
          requires:
            - build
      

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: chmod permissions
          command: sudo chmod +x ./gradlew
      - run: ./gradlew clean build
  test:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: ./gradlew test